### ISSUE TITLE
rider 的 edp 支持

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#11]
之前 `stylus` 是集成到 `edp` 中的，这样在升级时会遇到 `edp` 的 `stylus` 版本与项目不一致的问题，所以需要将这部分抽出来。

现在 `rider` 被设计为一个独立的 `npm` 模块，它是标准的 `stylus` 插件，本身是无任何依赖的（开发依赖不算）。

我设想的是写一个叫 `edp-provider-rider`（暂定名）的 `npm` 模块，将样式相关的工作流都集中起来处理，提供 `edp` 需要的 `webserver handler` 与 `build processor`。

这样每一个版本中的 `stylus`、`rider`、`autoprefixer` 版本都是正确匹配的，只要保证项目依赖的 `edp-provider-rider` 版本正确即可，不会受到 `edp` 升级的影响。

@treelite @junmer 看看有木有问题~

**Update**: @jummer 认领。

**Comment by treelite** [comment]
莫有问题～ `保证项目依赖`妥妥的

后续`less`也可以相应处理，以项目依赖为准~

**Comment by firede** [comment]
@junmer 目测完成了，帮你关上~
