### ISSUE TITLE
rider 重新实现 animate 部分

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#13]
之前 `archer` 的 `animate` 部分是基于 [animate.css](https://github.com/daneden/animate.css) 的封装，存在一些问题：
1. 无法控制动画的 **幅度**
2. 不能指定动画名，但 `@keyframes` 是会被提到 `root` 上的，不应该重名
3. `animate.css` 已经升级至 `3.x` 版本，需要跟进
4. `API` 需要优化

所以在 `rider` 中需要对之前的 `animate` 部分进行重写。

**Comment by treelite** [comment]
`saber-run`也需要弄下了，之前只是简单的做了下`transition`的处理

`rider的动画部分`和`saber-run`估计是有交集的，`saber-run`怎么搞还没想清楚...(>_<)...

**Comment by firede** [comment]
目前 `rider` 的动画部分还差 `animate` 部分，一堆 `@keyframes` 实现的 **动画效果**。

现在加了个 [`easing`](https://github.com/ecomfe/rider/blob/master/lib/rider/easing.styl)，扩充了 **缓动函数**（贝塞尔曲线） 供 `transition` 与 `animation` 使用。

我觉得 **[缓动函数](http://easings.net/zh-cn)** 效果的名称与参数是交集，应该尽量保持一致。

不过 JS 库通常把 `transition` 和 `animation` 封装一起，对外API保持统一。
但 CSS 库中 `transition` 和 `animation` 是分开的，所以上面链接中的缓动函数需要 `@keyframes` 的部分不会包含在 `rider` 的 `easing` 内。

**Comment by firede** [comment]
碰到些问题，第 `2` 条可能无法达成了：

`stylus` 的 `@keyframes` 灵活度较差，名称不接受 `string` 类型的值，只接受定义变量的变量名，想要这样做就智能写 `JavaScript` 来扩展 `stylus` 本身了，想想不值得，于是作罢~

**Comment by firede** [comment]
https://github.com/ecomfe/rider/commit/4b84181e8cb2c359492e8224a679b3564e5f8cf2
