### ISSUE TITLE
地理位置 saber-geo

### ISSUE THREAD

**Issue by junmer** [ecomfe/saber#14]
地理位置API

封装

  html5
  native app(百度地图)
  jsonp 后端 ip serv
  各种浏览器/壳 私有api

**Comment by zfkun** [comment]
收了~~

**Comment by junmer** [comment]
[lbs api](http://developer.baidu.com/map/ip-location-api.htm)

**Comment by zfkun** [comment]
感谢M君提供~ 
native adapter 有着落了
@guananddu

**Comment by junmer** [comment]
[geo-location-javascript](http://code.google.com/p/geo-location-javascript/)这个可以参考

**Comment by zfkun** [comment]
经过与 @guananddu 的讨论，先并行开发2个模块：
- `saber-geo/html5` : 对 [W3 Geolocation API](http://dev.w3.org/geo/api/spec-source.html)的封装
- `saber-geo/ip` : 提供`IP归属地查询`，默认源为 [hendless.duapp.com](http://hendless.duapp.com)

**Comment by zfkun** [comment]
`saber-geo/ip` done.

**Comment by zfkun** [comment]
`API`风格是否支持`Promise`或像`JQ`一样的`多态`？
https://github.com/ecomfe/saber-geo/issues/1

**Update 2014/04/03:**
先不支持，保持身材

**Comment by zfkun** [comment]
不错的`ip/hostname查询服务`，信息丰富(`经纬度`、`IP`、`地域`等等)，标记下~
http://freegeoip.net/

**Comment by zfkun** [comment]
### release 0.1.0
- [x] HTML5 Geolocation API
- [x] IP Search Server (JSONP)
- [ ] Browser Private API
- [ ] Native API
