### ISSUE TITLE
saber-uri URI处理工具

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#15]
URI 处理是个挺通用的需求，但是 `er` 选的 [`URI.js`](https://github.com/ecomfe/URI.js) 太重了，min + gzip 之后仍有 `13k`，所以需要一个功能简化的 URI 模块。

**Comment by treelite** [comment]
有人在搞莫，没有就我抢咯

**Comment by treelite** [comment]
[saber-uri](https://github.com/ecomfe/saber-uri) 构建中...
