### ISSUE TITLE
一堆常用功能的小需求

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#16]
项目中经常会有这样的需求：
- 将浏览器全屏，隐藏浏览器的地址栏
- 激活 `:active`，使其按下后有效果
- 返回页面顶部（带动画）
- 判断系统是否支持 fixed
- ...

先做下记录，欢迎补充，之后再研究模块划分。

@treelite @zfkun @redmed @junmer

**Comment by zfkun** [comment]
补充一个:
- 屏幕锁定(禁滚动)，可能用在 dialog、preview 等

**Comment by firede** [comment]
- `translate3d` 支持情况探测
