### ISSUE TITLE
touchjs 的 edp 体系支持

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#21]
给 [touchjs](https://github.com/brandnewera/touchjs) 提 `pull request`，以适应 `edp` 体系。

PS: 改造后将移除 `saber-touch` 包，直接使用 `touchjs`。

**Comment by firede** [comment]
结论是 `saber-touch` 将成为 `touchjs` 的一个分支，在最新版的基础上改造，融入 `saber` 体系。
并在适当的时候提 `PR` 回馈 `touchjs` 主项目。

接下来开始改造 `saber-touch`。

**Comment by firede** [comment]
对 `touchjs` 重构的时候发现这趋势越改越像 `hammer.js`，好纠结：
1. 封装 `touch` 类事件与 `mouse` 类事件，增加 `pointer` 类事件进行兼容
2. 更细粒度的进行模块划分，让各个部分职责更明确
3. 手势扩充，增加 `dragup`/`dargdown`/`dragleft`/`dragright` 更便捷的支持有中间态的定向滑动操作
4. 代码精简、优化，修正代码风格并去除无用的函数、变量
5. 构建测试用例，好让每次升级都心里有底

目前体积方面，gzip+min 之后 `hammer.js` 4.3k，`touchjs` 4.4k。
支持范围上 `hammer.js` 包含 windows phone 设备，`touchjs` 仅支持 webkit 内核，需要自己改造。

如果继续用 `touchjs` 还要做很多工作，但想要做的事情 `hammer.js` 都做了。
之前我给他们提过 PR，他们也支持 AMD 了，所以我有点想改用 `hammer.js`……

**Comment by treelite** [comment]
说个不靠谱的，赶脚直接动手写会比改造`touchjs`来得省，各方面都相对可控。如果有人想造轮子的话可以考虑，不然的话直接用`hammer.js`也挺好。

目前[saber-firework](https://github.com/ecomfe/saber-firework/tree/develop)也遇到同样的问题，也有直接用[vue.js](http://vuejs.org/)的冲动，忍了忍，先写着～

**Comment by firede** [comment]
嗯，如果有这方面的需求，就用 `hammer.js` 吧，它做的挺好的，手势库比较基础，和 `MV*` 框架不一样，所以没造轮子的理由。
