### ISSUE TITLE
移动开发手册目录

### ISSUE THREAD

**Issue by treelite** [ecomfe/saber#22]
关注移动开发整体流程的各个方面，确定文档大致涉及的各方面，完成大纲

**Comment by treelite** [comment]
目录初稿 [Guide](https://github.com/ecomfe/saber/wiki/Guide)

@ecomfe/mobile-team 大家先瞅瞅，明天下午有空的话讨论讨论～

**Comment by chf007** [comment]
手册中对框架的 MVP 是怎么运作没有说明，虽然按脚手架工具生成好了，但里边其实有许多约定，手册中没有体现出来。如何添加自已的Model，如何渲染自定义的模板，都没有说明。例如默认的startupnews例子，后台的数据拉回来后怎么渲染到模板里的完全看不出来。

建议增加一个从头到尾的简单教程，目前的教程只到了模板就没有了。

**Comment by treelite** [comment]
了解MVP框架的话，瞅瞅[saber-firework](https://github.com/ecomfe/saber-firework)吧，相关的说明都在这里。saber是模块化的解决方案，很多功能是由各个模块独立提供的，所以相关的说明可能瞅瞅各模块的文档会更清楚些～
