### ISSUE TITLE
增强 saber-lang 的功能

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#23]
目前 `saber-lang` 提供最基础的功能，main 中包含 `curry`、`bind`、`extend`、`inherits` 这四个最基本的方法，其余方法不会默认提供。

现在打算扩充 `saber-lang` 的范围，包含类似 `underscore/lodash` 中的常用功能，但为了优化体积，这些方法不会默认包含，必须使用类似 `require('saber-lang/array/zip')` 的方式引用。

**Comment by zfkun** [comment]
函数节流 `saber-lang/function/throttle` 添加中..

done. see [commit](https://github.com/ecomfe/saber-lang/commit/58e8fcf25802ad6a21f4b4c674d9d89eaab5b8cf)

**Comment by zfkun** [comment]
函数防抖 `saber-lang/function/debounce` 添加中..

done. see [commit](https://github.com/ecomfe/saber-lang/commit/58e8fcf25802ad6a21f4b4c674d9d89eaab5b8cf)

**Comment by firede** [comment]
结贴。目测现有的函数基本够用，以后再根据实际需要增加。
