### ISSUE TITLE
移动项目初始化模板 saber-boilerplate

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#27]
为每一个新创建的移动项目进行初始化。

这个项目是 App Framework、Base Component、CSS Library、UI Component 的整合，最后会被 Tools & Platform 做为 edp mobile init 的模板。

因为依赖各个子方向的进展，先记录下来，以后做。

**Comment by junmer** [comment]
是不是 可以先做一下 [h5bp mobile](https://github.com/h5bp/mobile-boilerplate/) 这种基础层级的准备

**Comment by firede** [comment]
我觉得可以，很多东西可以直接参考 h5bp mobile，但里面大多数是我们用不到的东西。
总之，我先创建个项目吧。

**Comment by treelite** [comment]
done
