### ISSUE TITLE
saber-emitter 是否需要支持异步事件

### ISSUE THREAD

**Issue by treelite** [ecomfe/saber#39]
如题，异步事件的场景常见吗？

**Comment by firede** [comment]
比如 `emit` 了某事件，要异步发 ajax 请求？
不过 `saber-ajax` 本身就是异步了……

其他的场景需要异步 `emitter` 的暂时木有想到，好像场景不多呀。

**Comment by treelite** [comment]
嗯 是说事件触发本身是异步触发的，比如：

``` javascript
a.emit('change');
// `change`事件回调在赋值语句之后触发
a.value = 'xxx';
```

实际就是有没有必要给事件触发加上`nextTick`之类的？想到这个是之前赶脚事件都应该是绝对异步的说

**Comment by firede** [comment]
了解，虽然按事件模型来看，感觉 `都是异步` 才 `正常`~
不过从 `Emitter` 实现上来说，我觉得同步还好，因为模型更简单，改成异步貌似收益不大。

真正需要 `non-blocking` 的事情用 `saber-promise` 来做就好了：

``` js
function doSomething () {
  var resolver = new Resolver();
  // ...
}
a.on('change', doSomething);
```

**Comment by firede** [comment]
不过我觉得如果碰到 `异步` 的需求可以给 `Emitter` 做个 `plugin`，把 `.emit` 重写了……

**Comment by treelite** [comment]
嗯 嗯 确实加了异步会更复杂，而且可能会有性能问题

那先不关心异步吧，等啥时候有强需求了再用`plugin`搞定吧
