### ISSUE TITLE
saber-env connection模块精简

### ISSUE THREAD

**Issue by zfkun** [ecomfe/saber#40]
因浏览器目前实现`较差`，暂时移除[新规范](http://www.w3.org/TR/netinfo-api/)的兼容部分。

**Comment by zfkun** [comment]
done. see [commit](https://github.com/ecomfe/saber-env/commit/c4c941ac3c6926d354714a551a417ed36f867d66)

**Comment by firede** [comment]
:+1: 赞，刚好现在的项目就能用到了！
