### ISSUE TITLE
Android 2.3.7 下 Jasmine 不执行 spec

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#50]
升级 Jasmine 2.0 后第一次在 Android 2.3 下跑单测，发现 spec 没有被执行：

![image](https://cloud.githubusercontent.com/assets/157338/2607609/98644c8e-bb5f-11e3-80f9-cc909bcfad9c.png)

绝大多数时候 specs 都是 0，偶尔能刷出第一个 spec 文件的用例。
环境是 Android 2.3.7，因为没有真机，在 Genymotion 模拟器下测的。

**Comment by treelite** [comment]
初步看是`spec`异步加载导致引起的，`boot.js`中在`window.onload`时启动的测试，此时可能`spec`还未加载完，靠谱的方式是在全局`require`的回调中启动测试，需要修改下`boot.js`

为啥这问题只在`android 2.3`中遇到了呢...

**Comment by treelite** [comment]
PS：真机测试`2.3`，修改`boot.js`后好使了...

**Comment by firede** [comment]
那回头在 `saberlabs/static` 中加个 `amd-boot.js`？

**Comment by treelite** [comment]
嗯 好的 我来搞～

发自我的 iPhone

**Comment by treelite** [comment]
在`saberlabs/static`中添加了`amd-boot.js`，使用的是显式声明具名`Module`的方式，需要保证加载顺序在`esl`后，并在所有`spec`加载完成后再手动启动`jasmine`，如下：

``` javascript
require(['boot', 'module.spec'], function (boot) {
    boot();
});
```

具体可以参考`saberlabs/static`的[README](https://github.com/saberlabs/static)，或者`saber-uri`的[test/runner.html](https://github.com/ecomfe/saber-uri/blob/master/test/runner.html)
