### ISSUE TITLE
关于 saber-lang 增加aop可选模块的实现

### ISSUE THREAD

**Issue by zfkun** [ecomfe/saber#52]
准备给 `saber-lang` 增加一个 `aop` 的可选模块 `saber-lang/function/aspect`
对于具体的实现，目前有一些需求点，这里继续讨论吧。

下面列举一些提到的需求点:
1. 无侵入，单纯的工具函数，直接返回包装后的`新函数`
2. 有侵入，`原函数`会被构造的`新函数`覆盖
3. 可改参，`before`, `after`的形参与`原函数`保持一致且不能修改，通过返回`[...]`作为下一个函数形参的方式达到`动态修改输入参数`
4. 可中断，当`before`包装函数返回`false`时，停止后续的所有函数调用

抛砖一下，慢慢讨论

@ecomfe/mobile-team

**Comment by zfkun** [comment]
根据 `2`、`4` 完成了一个版本，[see doc](https://github.com/ecomfe/saber-lang/tree/develop#aspectmixin-obj-)

**Comment by firede** [comment]
:+1:
我觉得能满足普通 AOP 场景的需要了（统计、权限拦截等），等整体发版的时候我把 `saber-emitter/aspect` 干掉。

@treelite 看看？
我觉得普通 AOP 场景不改参更合适些，这样能在结构上减少对原功能的影响。
如果你那边有改参需求，单独实现可能更方便点儿。

**Comment by treelite** [comment]
嗯 好的 

想了想 改变参数不太通用 弊大于利 就这么搞吧 之后如果遇到强需求再考虑～

**Comment by zfkun** [comment]
话说，可选的 `context` 参数，**使用得当**也可以达到`改参`所要的效果。
那就这么着了，结贴~
