### ISSUE TITLE
saber对windows phone下ie的支持不好

### ISSUE THREAD

**Issue by li-yinan** [ecomfe/saber#56]
体验了一下demo，发现了以下问题：
1、转场严重卡顿
2、转场出现横向滚动条
3、顶栏返回按钮无效
4、刷新页面有概率停留在logo页不能进入列表页面

环境：nokia 720T，windows phone 8.1， 原生ie浏览器，开启了“向您访问的网站发送请勿跟踪请求”

**Comment by firede** [comment]
目前还没对 WP 做兼容（主要是因为木有设备），节后优化一下 WP 下的表现~
