### ISSUE TITLE
使用 `rider` 的项目中存在 `rider.styl` 文件时引起的解析出错问题

### ISSUE THREAD

**Issue by zfkun** [ecomfe/saber#59]
又踩一深坑 ~

使用 `rider` 的项目中(比如 `rider-ui`)，若存在名叫 `rider.styl` 的文件，
则会造成 `rider.js` 中 `style.import( 'rider' )` 发生**致命错误**

> 比如在 `rider-ui/demo` 或 `rider/demo/public` 下创建个 `rider.styl` 空文件

目测，可能是`搜索路径优先级`引起的

@ecomfe/mobile-team

**Comment by firede** [comment]
我觉得这个不算 bug，因为隐式引入 rider 实际上相当于自动帮你做了：

```
@import 'rider'
```

在开发中就要避开 `rider` 目录或文件了，就像引入了 jQuery 之后就不应该再去重定义 `$` 一样。
