### ISSUE TITLE
edp mobile start 的异常被吞掉了

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#61]
有时候运行 edp webserver/watch 会出错，而 start 命令没有把错误抛出来，就比较难定位问题。（如：项目目录没有安装 edp-provider-rider 时）

@junmer

**Comment by junmer** [comment]
目前可以 这么实现

```
/**
 * require with try catch
 *
 * @param  {string} mod modname
 * @return {any}     mod
 */
function requireSafely(mod) {
    try {
        return require(mod);
    }
    catch (e) {
        log.error(e);
        return;
    }
}
```

但是 感觉很 2 ，正在寻找更优秀解

**Comment by junmer** [comment]
[nodejs-error-handling-pattern](http://www.nodewiz.biz/nodejs-error-handling-pattern/) 参考下

**Comment by firede** [comment]
直接取 spawn 后的 `ChildProcess object`，然后监视 `stdout`，内容直接输出呢？
