### ISSUE TITLE
给 saber 做了个 logo

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#7]
<p align="center"><img src="https://f.cloud.github.com/assets/157338/1476550/a853833c-464b-11e3-9d44-e784b08da98f.png" alt="saber" /></p>

<p align="center">取 <strong>石中剑</strong> 之意，测一下效果</p>

**Comment by treelite** [comment]
把edp上的头像换成这个吧～～

**Comment by firede** [comment]
@treelite 不行啊，我们不是单独的 organization，saber只是组织的一部分……

**Comment by treelite** [comment]
@firede 不是这个意思啦 没阐述清楚...(>_<)... 实际意思是说edp仓库上saber用户名的头像换成这个～

**Comment by firede** [comment]
@treelite 哦哦，这个可以，那我优化下logo，这就换！

**Comment by firede** [comment]
![logo-github](https://f.cloud.github.com/assets/157338/1485433/aeb5c72a-4714-11e3-87ae-7ef8ae66e605.png)
260px \* 100px
![logo-only-100](https://f.cloud.github.com/assets/157338/1485281/a6259718-4712-11e3-949e-16155963c947.png)
100px
![logo-only-115](https://f.cloud.github.com/assets/157338/1485282/a69d25a8-4712-11e3-8c99-3ba95f9d13d0.png)
115px
![logo-only-230](https://f.cloud.github.com/assets/157338/1485283/a69d6ac2-4712-11e3-81ad-8406871bf455.png)
230px
![icon-only-460](https://f.cloud.github.com/assets/157338/1485284/a6edac9e-4712-11e3-9906-0c84621c677e.png)
460px

传几个新版本留着各种地方用 :yum:

**Comment by zfkun** [comment]
雷哥给力！！ 不过。。。第一眼当成了坟墓，太像十字架了。。。(>_<)
