### ISSUE TITLE
路由规则支持正则表达式，自动注入参数

### ISSUE THREAD

**Issue by mycoin** [ecomfe/saber#71]
路由规则配置文件，支持『正则表达式』
{
{path: '^/welcome/index/(:category)/(:page)', action: require('./welcome/index')}
}
然后自动注入到 Model

不知道这个有没有用哇~ ~~~~~

PS： edp mobile add xxx 的时候，会把 path 为正则表达式的item搞错~~

**Comment by treelite** [comment]
目前是支持正则表达式的，如果要支持参数的话建议使用`RESTful`风格，比如直接写成:

``` javascript
{
    path: '/welcome/index/:category/:page', action: require('./welcome/index')
}
```

参数`category`与`page`会出现在`action`的`query`参数中，`model`可以通过`fetch`方法获取到，暂时没有自动注入到`model`，后续会考虑适当的方式自动注入

嗯 `edp mobile add` 目前还不支持正则的形式 ...(>_<)...

**Comment by treelite** [comment]
考虑再三 还是暂时不在[1.0.0](https://github.com/ecomfe/saber-firework/blob/master/History.md#100--2014-11-03)中提供`model`参数自动注入的，后续版本再考虑吧...
