### ISSUE TITLE
saber-router 支持改url后不重刷action

### ISSUE THREAD

**Issue by kekee000** [ecomfe/saber#72]
需求是 希望增加改url中params的接口，但是不作任何动作，这样回退的时候能够回退到之前的筛选

或者增加与er类似的render，refresh机制，改参数后不重刷action

**Comment by treelite** [comment]
action增加了`refresh`机制，为了向下兼容及为简单页面考虑，如果页面没有设置`refresh`函数则保持原有逻辑，重新render页面

**Comment by treelite** [comment]
see [saber-firework@1.0.0](https://github.com/ecomfe/saber-firework/blob/master/History.md#100--2014-11-03)
