### ISSUE TITLE
saber-env 增加壳浏览器、网络链接方式探测

### ISSUE THREAD

**Issue by firede** [ecomfe/saber#8]
现在的 `saber-env` 是直接从 `Zepto` 中提取出来的，不包含国内主流壳浏览器，如UC、QQ、百度浏览器等。

实际开发中，不同壳浏览器还是有识别需求的（比如iOS的UC浏览器，单页面WebApp转场的表现与其它浏览器有差异）。

**Update 2014-02-25:**
另外，增加对 `navigator.connection` 的封装，识别当前网络链接方式。

**Comment by firede** [comment]
另外，可以增加音频视频（`audio`/`video`）支持资源类型的探测（`.canPlayType` API），做为可选部分提供。

**Comment by zfkun** [comment]
收了~

一份13年的UA参考文档(内部)：http://wiki.babel.baidu.com/twiki/bin/view/Main/UserAgent

**Comment by zfkun** [comment]
- UC、QQ、百度 壳浏览器探测支持
- navigator.connection 封装支持

done.

**Update 2014-03-21:**
增加 `搜狗`、`猎豹`、`mercury` 、`小米` 识别

**Comment by zfkun** [comment]
新增 `audio`、`video`的`.canPlayType( type )` API支持
see [commit](https://github.com/ecomfe/saber-env/commit/2cbc1eb2689ca2104e8f51f4b9db6533edc4285b)

**Comment by firede** [comment]
赞~！
把 `saber-env` 的 `maintainers` 改成你吧，我到 `contributors` 里打酱油就好 :fish:

**Comment by firede** [comment]
另外建议将 `connection` 支持未成熟部分去掉，防止使用者采坑~

**Comment by zfkun** [comment]
~ ~!  好类，我的酱油~~~

**Comment by zfkun** [comment]
done. see [commit](https://github.com/ecomfe/saber-env/commit/c4c941ac3c6926d354714a551a417ed36f867d66)
