### ISSUE TITLE
模板加载不成功，require时会自动加上.js

### ISSUE THREAD

**Issue by chf007** [ecomfe/saber#81]
使用saber创建好一个默认项目后，模板加载不成功，因为require时会自动加上.js，而默认创建的模板是以.tpl结尾的

**Comment by firede** [comment]
如果是用 edp mobile 创建的项目，在 `edp-webserver-config.js` 中会有下面这一段配置：

```
{
    location: /^[^\?]+?\.tpl\.js($|\?)/,
    handler: [
        html2js()
    ]
},
```

将 `.tpl.js` 结尾的请求转给 `html2js`，找到同名的 `.tpl` 模板，转换为 AMD 模块并返回。

请检查一下，是否是用 `edp mobile start` 启动的调试服务器？
使用其它的服务器，不会自动做如上处理。

**Comment by chf007** [comment]
恩，是用 edp mobile 创建的项目，但不是用 edp mobile start 启动的，因为不是自已完全控制的服务器，有些命令执行不了。

这样的话，我自已去找 html2js 手动转换一下就行？

是用的这个么？ https://github.com/junmer/html2js

**Comment by firede** [comment]
还是建议在本地搭建开发环境，Windows 下装个二进制版的 node，然后用 npm 安装 edp 就可以。
需要线上环境时，再将 build 之后的版本上传至服务器。

**Comment by chf007** [comment]
好的，简单用了下，这个开发单页应用非常方便，赞一下。使用中有什么问题随时沟通。

**Comment by firede** [comment]
:ok_hand:
