### ISSUE TITLE
在View的domEvents中绑定blur事件无效

### ISSUE THREAD

**Issue by zwsf** [ecomfe/saber#84]
'blur: .selector': function (el) {
      // todos
 },
这么绑定无效，最后在ready中使用addEventListener方式绑定成功，是否对dom事件支持不太完全？

**Comment by firede** [comment]
冒号后的空格去掉试试：
`'blur: .selector'` => `'blur:.selector'`

**Comment by treelite** [comment]
在 View 的配置中使用 `domEvents` 属性定义事件是基于事件代理来完成的，这里确实没有对 `blur` 这种不冒泡的事件做特殊处理，所以在处理这些事件时请使用 [addDomEvent](https://github.com/ecomfe/saber-mm/blob/master/doc/view.md#adddomeventele-type-selector-fn) 方法

**Comment by zwsf** [comment]
赞，文档还是没看细，继续看去..
