### ISSUE TITLE
saber-viewport初始化视口时设置viewport.style.position='relative'有什么特别的作用吗？

### ISSUE THREAD

**Issue by zwsf** [ecomfe/saber#85]
如题，最近一个页面主体是一个可以上拉加载下拉刷新的列表，底部footer固定悬浮，因为内嵌到app中所以不需要header。在主体列表的布局中因为有viewport的定位致使出现了无法上下滑动，于是去除了viewport元素的定位，这个地方的预设有什么特殊的作用吗？如果有我需要对当前页面的布局进行调整

**Comment by treelite** [comment]
viewport 的 `relative` 定位是为了使视图内的 `absolute` 默认相对于视图来定位，视图是一个容器，内部元素不应该受容器以外元素的影响

另外具体是一个怎样的滑动呀？想不到 `relative` 的设置会影响滚动的原因 ...

**Comment by zwsf** [comment]
囧...我又把打开viewport的相对定位，页面没问题，应该是开发的时候我业务代码的问题，跟saber-viewport的视口定位没关系。项目是个内嵌到app里面的h5页面，还没上线，没法发线上地址还
